name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go 1.16
      uses: actions/setup-go@v2
      with:
          go-version: 1.16
    - name: Test Go-RFC1751
      run: go test . -v
